service: gognito-website

provider:
  name: aws
  runtime: nodejs8.10

  stage: develop
  region: us-east-1 # Lambda@Edge function must be us-east-1

  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
  
  variableSyntax: "\\${(?!AWS::)([ :a-zA-Z0-9._,\\-\\/\\(\\)]+?)}"

plugins:
  - serverless-plugin-cloudfront-lambda-edge
  - serverless-s3-sync

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  s3Sync:
    - bucketName: ${env:S3_BUCKET_NAME}
      localDir: build

package:
  exclude:
    - src/*
    - test/*
    - package.json
    - README.md

functions:
  basicAuth:
    name: gognito-website-basicAuth-${self:custom.stage}
    handler: handler.basicAuth
    memorySize: 128
    timeout: 1
    lambdaAtEdge:
      distribution: WebsiteDistribution
      eventType: 'viewer-request'

resources: ${file(./resources.yml)}
